

#router 7

ip -6 route add 2001:1200:0:21f1::/64 dev eth1
ip -6 route add fd01:1200:0:21f1::/64 dev eth1


# auto-generated by RADVD service (utility.py)

interface eth1
{
	AdvSendAdvert on;
        MinRtrAdvInterval 3;
        MaxRtrAdvInterval 10;
        AdvDefaultPreference low;
	AdvHomeAgentFlag off;
	prefix 2001:1200:0:21f1::/64;
	prefix fd01:1200:0:21f1::/64 
	{
		AdvOnLink on;
		AdvAutonomous on;
		AdvRouterAddr on;
	};
};


#################################################
################################################

#router 8

ip -6 route add 2001:1200:0:21f0::/64 dev eth1
ip -6 route add fd01:1200:0:21f0::/64 dev eth1


# auto-generated by RADVD service (utility.py)

interface eth1
{
	AdvSendAdvert on;
        MinRtrAdvInterval 3;
        MaxRtrAdvInterval 10;
        AdvDefaultPreference low;
	AdvHomeAgentFlag off;
	prefix 2001:1200:0:21f0::/64;
	prefix fd01:1200:0:21f0::/64
	{
		AdvOnLink on;
		AdvAutonomous on;
		AdvRouterAddr on;
	};
};


#################################################
################################################

#router 5

ip -6 route add 2001:1200:0:21f3::/64 dev eth3
ip -6 route add fd01:1200:0:21f3::/64 dev eth3


# auto-generated by RADVD service (utility.py)

interface eth3
{
	AdvSendAdvert on;
        MinRtrAdvInterval 3;
        MaxRtrAdvInterval 10;
        AdvDefaultPreference low;
	AdvHomeAgentFlag off;
	prefix 2001:1200:0:21f3::/64;
	prefix fd01:1200:0:21f3::/64
	{
		AdvOnLink on;
		AdvAutonomous on;
		AdvRouterAddr on;
	};
};



#################################################
################################################

#router 1

ip -6 route add 2001:1200:0:21f2::/64 dev eth1
ip -6 route add fd01:1200:0:21f2::/64 dev eth1


# auto-generated by RADVD service (utility.py)

interface eth1
{
	AdvSendAdvert on;
        MinRtrAdvInterval 3;
        MaxRtrAdvInterval 10;
        AdvDefaultPreference low;
	AdvHomeAgentFlag off;
	prefix 2001:1200:0:21f2::/64;
	prefix fd01:1200:0:21f2::/64
	{
		AdvOnLink on;
		AdvAutonomous on;
		AdvRouterAddr on;
	};
};

#################################################
################################################

#router 9

ip -6 route add fd01:1200:0:21f5::/64 dev eth3
ip -6 route add fd01:1200:0:21f6::/64 dev eth2



# auto-generated by RADVD service (utility.py)

interface eth3
{
	AdvSendAdvert on;
        MinRtrAdvInterval 3;
        MaxRtrAdvInterval 10;
        AdvDefaultPreference low;
	AdvHomeAgentFlag off;
	prefix fd01:1200:0:21f5::/64
	{
		AdvOnLink on;
		AdvAutonomous on;
		AdvRouterAddr on;
	};
};

interface eth2
{
	AdvSendAdvert on;
        MinRtrAdvInterval 3;
        MaxRtrAdvInterval 10;
        AdvDefaultPreference low;
	AdvHomeAgentFlag off;
	prefix fd01:1200:0:21f6::/64
	{
		AdvOnLink on;
		AdvAutonomous on;
		AdvRouterAddr on;
	};
};


#################################################
################################################

#router casa

ip -6 route add 2001:1200:0:21f4::/64 dev eth1
ip -6 route add fd01:1200:0:21f4::/64 dev eth1


# auto-generated by RADVD service (utility.py)

interface eth1
{
	AdvSendAdvert on;
        MinRtrAdvInterval 3;
        MaxRtrAdvInterval 10;
        AdvDefaultPreference low;
	AdvHomeAgentFlag off;
	prefix 2001:1200:0:21f4::/64;
	prefix fd01:1200:0:21f4::/64
	{
		AdvOnLink on;
		AdvAutonomous on;
		AdvRouterAddr on;
	};
};